name: Build Image

on: 
  #push:
  #  branches:
  #    - main
  #schedule:
  #  - cron: '52 23 3 * *'
  workflow_dispatch:
    inputs:
      mode:
        description: 'Manual Build'  
        
env:
  IMAGE_REGISTRY: "ghcr.io"

  
jobs:

  Build-Push:
    runs-on: ubuntu-latest
    steps:
    
    - name: "Set environmental variables"
      run: |
        echo "IMAGE=${IMAGE_REGISTRY}/${GITHUB_REPOSITORY}:${GITHUB_REF_NAME}" >> $GITHUB_ENV
    
    - name: Checkout Code
      uses: actions/checkout@v3   

    - name: Build Local Container
      run: |
        docker build . --file Dockerfile --tag ${IMAGE}
                
    - name: Login to Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${IMAGE_REGISTRY} -u ${GITHUB_ACTOR} --password-stdin

    - name: Push Docker Image
      run: |
        docker push ${IMAGE}
        
        

